version: '3.8'

services:
  # MySQL 数据库服务
  database:
    image: mysql:8.0
    container_name: elearning-db-dev
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: elearning
      MYSQL_USER: elearning_user
      MYSQL_PASSWORD: elearning_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_dev:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/seeds:/docker-entrypoint-initdb.d/seeds
    networks:
      - elearning-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Spring Boot 后端服务
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: elearning-backend-dev
    environment:
      SPRING_PROFILES_ACTIVE: development
      DB_HOST: database
      DB_PORT: 3306
      DB_NAME: elearning
      DB_USERNAME: elearning_user
      DB_PASSWORD: elearning_pass
      JWT_SECRET: dev-jwt-secret-key-please-change-in-production
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./backend/src:/app/src
      - ./backend/target:/app/target
    networks:
      - elearning-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Vue.js 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: elearning-frontend-dev
    environment:
      VITE_API_BASE_URL: http://localhost:8080/api/v1
      VITE_APP_TITLE: Contoso E-Learning Platform (Dev)
      VITE_APP_DEBUG: true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - /app/node_modules
    networks:
      - elearning-network
    depends_on:
      - backend

volumes:
  mysql_data_dev:
    driver: local

networks:
  elearning-network:
    driver: bridge