name: Frontend CI/CD - Azure AKS

on:
  pull_request:
    # branches: [main, develop]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-deploy.yml'
      - 'deployment/aks/frontend/**'
  push:
    branches: [main]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-deploy.yml'
      - 'deployment/aks/frontend/**'

env:
  AZURE_CONTAINER_REGISTRY: democrhk
  CONTAINER_NAME: elearning-frontend
  RESOURCE_GROUP: DemoAKS-RG-HK
  CLUSTER_NAME: demoaks-hk
  DEPLOYMENT_MANIFEST_PATH: 'deployment/aks/frontend'
  ACR_LOGIN_SERVER: democrhk.azurecr.io

jobs:
  build:
    runs-on: ubuntu-latest
    
    outputs:
      # 避免直接输出包含注册表URL的标签，只输出纯标签部分
      image-tag: ${{ steps.extract-tag.outputs.tag }}
      image-digest: ${{ steps.build.outputs.digest }}
      should-push: ${{ steps.should_push.outputs.should_push }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'

    - name: Install dependencies
      working-directory: ./frontend
      run: npm ci

    - name: Run type checking
      working-directory: ./frontend
      run: npm run type-check

    - name: Build application
      working-directory: ./frontend
      run: npm run build

    # Only build and push Docker image on main branch or when secrets are available
    - name: Check if push is needed
      id: should_push
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          echo "should_push=true" >> $GITHUB_OUTPUT
        else
          echo "should_push=false" >> $GITHUB_OUTPUT
        fi

    # Azure Container Registry login (only when pushing)
    - name: Azure Container Registry login
      if: steps.should_push.outputs.should_push == 'true'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME || 'dummy-user' }}
        password: ${{ secrets.ACR_PASSWORD || 'dummy-password' }}

    # Extract metadata for Docker image
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.ACR_LOGIN_SERVER }}/${{ env.CONTAINER_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr,prefix=pr-
          type=raw,value=latest,enable={{is_default_branch}}

    # 提取纯标签部分（避免敏感信息警告）
    - name: Extract clean tag
      id: extract-tag
      run: |
        # 获取第一个标签并提取纯标签部分
        FULL_TAGS="${{ steps.meta.outputs.tags }}"
        FIRST_TAG=$(echo "$FULL_TAGS" | head -n1)
        
        # 提取标签部分（冒号后的部分）
        TAG_ONLY=$(echo "$FIRST_TAG" | cut -d':' -f2)
        
        # 输出到GITHUB_OUTPUT，只包含标签，不包含注册表URL
        echo "tag=$TAG_ONLY" >> $GITHUB_OUTPUT
        
        # 用于调试的日志输出
        echo "::notice::Extracted tag: $TAG_ONLY"
        echo "::debug::Full tag was: $FIRST_TAG"

    # 强制显示输出（用于验证）
    - name: Display outputs
      run: |
        echo "::notice::Build outputs:"
        echo "::notice::  tag: ${{ steps.extract-tag.outputs.tag }}"
        echo "::notice::  should-push: ${{ steps.should_push.outputs.should_push }}"

    # Build and push Docker image (only on main branch)
    - name: Build and push Docker image
      id: build
      if: steps.should_push.outputs.should_push == 'true'
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          VITE_API_BASE_URL=https://localhost:8000/api
          VITE_APP_TITLE=Contoso E-Learning Platform

    # Build only for PR (no push)
    - name: Build Docker image (PR only)
      if: steps.should_push.outputs.should_push == 'false'
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: false
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          VITE_API_BASE_URL=http://localhost:8000/api
          VITE_APP_TITLE=Contoso E-Learning Platform

  security-scan:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'pull_request'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # 显示接收到的标签信息
    - name: Display tag information
      run: |
        echo "::notice::Received image tag: ${{ needs.build.outputs.image-tag }}"
        echo "::notice::Should push: ${{ needs.build.outputs.should-push }}"
        echo "Security scan will use tag: ${{ needs.build.outputs.image-tag }}"

    # 运行基本的安全扫描（这里可以扩展为真实的Trivy扫描）
    - name: Run Trivy security scan
      run: |
        echo "🔒 Running security scan for PR"
        echo "📦 Image tag: ${{ needs.build.outputs.image-tag }}"
        echo "✅ Security scan completed successfully"
        
        # 这里可以添加实际的Trivy命令
        # docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
        #   aquasec/trivy:latest image local-image:${{ needs.build.outputs.image-tag }}

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    environment: production
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'
    
    - name: Get AKS credentials
      run: |
        az aks get-credentials --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.CLUSTER_NAME }}
    
    - name: Create namespace if not exists
      run: |
        kubectl apply -f deployment/aks/frontend/01-namespace.yaml
    
    - name: Apply ConfigMaps and Secrets
      run: |
        kubectl apply -f deployment/aks/frontend/02-configmap.yaml
    
    - name: Extract image tag from build output
      id: image_info
      run: |
        # 使用从build job传递的纯标签
        IMAGE_TAG="${{ needs.build.outputs.image-tag }}"
        FULL_IMAGE="${{ env.ACR_LOGIN_SERVER }}/${{ env.CONTAINER_NAME }}:${IMAGE_TAG}"
        
        echo "Using image tag: $IMAGE_TAG"
        echo "Full image name: $FULL_IMAGE"
        
        echo "full_image=$FULL_IMAGE" >> $GITHUB_OUTPUT
        echo "tag_only=$IMAGE_TAG" >> $GITHUB_OUTPUT
    
    - name: Update deployment image
      run: |
        # Create a backup of the original file
        cp deployment/aks/frontend/03-deployment.yaml deployment/aks/frontend/03-deployment.yaml.backup
        
        # Update deployment manifest with the actual built image tag
        # Use single quotes and escape properly to avoid YAML issues
        sed -i 's|#{ACR_LOGIN_SERVER}#|${{ env.ACR_LOGIN_SERVER }}|g' deployment/aks/frontend/03-deployment.yaml
        sed -i 's|#{IMAGE_TAG}#|${{ steps.image_info.outputs.tag_only }}|g' deployment/aks/frontend/03-deployment.yaml
        
        # For URL replacement, ensure proper quoting
        API_BASE_URL="https://api.elearning.demo.com"
        sed -i "s|#{VITE_API_BASE_URL}#|${API_BASE_URL}|g" deployment/aks/frontend/03-deployment.yaml
        
        echo "=== Updated deployment manifest ==="
        cat deployment/aks/frontend/03-deployment.yaml | grep -A 10 -B 5 "image:"
        
        echo "=== Environment variables section ==="
        cat deployment/aks/frontend/03-deployment.yaml | grep -A 10 -B 2 "VITE_API_BASE_URL"
        
        echo "=== Validating YAML syntax ==="
        kubectl apply --dry-run=client -f deployment/aks/frontend/03-deployment.yaml
        
        echo "Using full image: ${{ steps.image_info.outputs.full_image }}"
        echo "Using tag: ${{ steps.image_info.outputs.tag_only }}"
    
    - name: Deploy application
      run: |
        # Apply all manifests in order
        echo "Applying deployment manifest..."
        kubectl apply -f deployment/aks/frontend/03-deployment.yaml
        
        echo "Applying service manifest..."
        kubectl apply -f deployment/aks/frontend/04-service.yaml
        
        echo "Applying ingress manifest..."
        kubectl apply -f deployment/aks/frontend/05-ingress.yaml
        
        echo "Applying HPA manifest..."
        kubectl apply -f deployment/aks/frontend/06-hpa.yaml
        
        echo "Checking deployment status..."
        kubectl get deployments -n elearning
       # kubectl apply -f deployment/aks/frontend/07-network-policy.yaml
    
    - name: Wait for deployment rollout
      run: |
        kubectl rollout status deployment/elearning-frontend -n elearning --timeout=600s
    
    - name: Verify deployment health
      run: |
        echo "Checking pod status..."
        kubectl get pods -n elearning -l app=elearning-frontend
        
        echo "Checking service status..."
        kubectl get svc -n elearning -l app=elearning-frontend
        
        echo "Checking ingress status..."
        kubectl get ingress -n elearning
        
        echo "Checking HPA status..."
        kubectl get hpa -n elearning
        
        # Wait for pods to be ready
        kubectl wait --for=condition=ready pod -l app=elearning-frontend -n elearning --timeout=300s
